// TODO: Include packages needed for this application
const inquirer = require('inquirer');
const fs = require('fs');
// TODO: Create an array of questions for user input
const questions = [];

// TODO: Create a function to write README file
function writeToFile(fileName, data) {}

// TODO: Create a function to initialize app
function init() {}

// Function call to initialize app
init();


//REMEMBER README FILE IS ALL TEXT MAKE A STRING USING TEMPLATE LITERALS
//HAVE TO RECORD MYSELF RUNNING THIS IN MY TERMINAL
//USE SOME SCREEN RECORDING
//PUT A LINK TO VIDEO IN SUBMISSION
//GOOGLEDRIVE MAYBE
//STILL HAVE TO MAKE A README FILE FOR THIS PROJECT
//WILL ALSO HAVE TO SUBMIT A SAMPLE README THAT IS GENERATED BY ASSIGNMENT
//THERE IS NOTHING TO DEPLOY