//Include packages needed for this application
const inquirer = require('inquirer');
const fs = require('fs');
const generateMarkdown = require('./utils/generateMarkdown.js');
//Create an array of questions for user input
const questions = [
    {
        type: 'input',
        message: 'Please enter the title of your project.',
        name: 'title',
    },

    {
        type: 'input',
        message: 'Please enter a description of your project.',
        name: 'description',
    },
    {
        type: 'input',
        message: 'Please enter installations instuctions.',
        name: 'installationInstructions',
    },
    {
        type: 'input',
        message: 'Please enter usage information.',
        name: 'usageInformation',
    },
    {
        type: 'input',
        message: 'Please enter the contribution guidelines.',
        name: 'contributionGuidelines',
    },
    {
        type: 'input',
        message: 'Please enter the test instructions.',
        name: 'testInstructions',
    },
    {
        type: 'list',
        message: 'Which license would you like to add?',
        name: 'license',
        choices: ['MIT License', 'Apache License 2.0', 'GNU GPL v3','Mozilla Public License 2.0','BSD 3-Clause License']
    },
    {
        type: 'input',
        message: 'Please enter your GitHub name.',
        name: 'githubName',
    },
    {
        type: 'input',
        message: 'Please enter your email address.',
        name: 'email',
    }
];

//   Example of using async/await with inquirer
async function readmeDetails() {
    const data = await inquirer.prompt(questions);
    console.log(data);
    const genReadme = generateMarkdown(data);
    writeToFile('README.md', genReadme);
}

// TODO: Create a function to write README file
function writeToFile(fileName, data) { 
    fs.writeFile(fileName, data, (err) =>
        err ? console.error(err) : console.log('Success!')
    )
}

// TODO: Create a function to initialize app
function init() {
    readmeDetails();
}

// Function call to initialize app
init();


//REMEMBER README FILE IS ALL TEXT MAKE A STRING USING TEMPLATE LITERALS
//HAVE TO RECORD MYSELF RUNNING THIS IN MY TERMINAL
//USE SOME SCREEN RECORDING
//PUT A LINK TO VIDEO IN SUBMISSION
//GOOGLEDRIVE MAYBE
//STILL HAVE TO MAKE A README FILE FOR THIS PROJECT
//WILL ALSO HAVE TO SUBMIT A SAMPLE README THAT IS GENERATED BY ASSIGNMENT
//THERE IS NOTHING TO DEPLOY